apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-go-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: template-go-service
  replicas: 1
  template:
    metadata:
      labels:
        run: template-go-service
    spec:
      containers:
      - name: template-go-service
        image: keptn/template-go-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: EVENTBROKER
          value: 'http://event-broker.keptn.svc.cluster.local/keptn'
---
apiVersion: v1
kind: Service
metadata:
  name: template-go-service
  namespace: keptn
  labels:
    run: template-go-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: template-go-service
